// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo.proto

package io.github.dunwu.javacore.serialize.stream;

public final class DemoProtos {
  private DemoProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * int 类型
     * </pre>
     *
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <pre>
     * string 类型
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <pre>
     * string 类型
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string email = 3;</code>
     * @return The email.
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 3;</code>
     * @return The bytes for email.
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <pre>
     * 引用下面定义的 Gender 枚举类型
     * </pre>
     *
     * <code>.User.Gender gender = 4;</code>
     * @return The enum numeric value on the wire for gender.
     */
    int getGenderValue();
    /**
     * <pre>
     * 引用下面定义的 Gender 枚举类型
     * </pre>
     *
     * <code>.User.Gender gender = 4;</code>
     * @return The gender.
     */
    io.github.dunwu.javacore.serialize.stream.DemoProtos.User.Gender getGender();

    /**
     * <pre>
     * 引用下面定义的 PhoneNumber 类型的 message
     * </pre>
     *
     * <code>repeated .User.PhoneNumber phone = 5;</code>
     */
    java.util.List<io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber> 
        getPhoneList();
    /**
     * <pre>
     * 引用下面定义的 PhoneNumber 类型的 message
     * </pre>
     *
     * <code>repeated .User.PhoneNumber phone = 5;</code>
     */
    io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber getPhone(int index);
    /**
     * <pre>
     * 引用下面定义的 PhoneNumber 类型的 message
     * </pre>
     *
     * <code>repeated .User.PhoneNumber phone = 5;</code>
     */
    int getPhoneCount();
    /**
     * <pre>
     * 引用下面定义的 PhoneNumber 类型的 message
     * </pre>
     *
     * <code>repeated .User.PhoneNumber phone = 5;</code>
     */
    java.util.List<? extends io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumberOrBuilder> 
        getPhoneOrBuilderList();
    /**
     * <pre>
     * 引用下面定义的 PhoneNumber 类型的 message
     * </pre>
     *
     * <code>repeated .User.PhoneNumber phone = 5;</code>
     */
    io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumberOrBuilder getPhoneOrBuilder(
        int index);

    /**
     * <pre>
     * map 类型
     * </pre>
     *
     * <code>map&lt;string, string&gt; tags = 6;</code>
     */
    int getTagsCount();
    /**
     * <pre>
     * map 类型
     * </pre>
     *
     * <code>map&lt;string, string&gt; tags = 6;</code>
     */
    boolean containsTags(
        java.lang.String key);
    /**
     * Use {@link #getTagsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getTags();
    /**
     * <pre>
     * map 类型
     * </pre>
     *
     * <code>map&lt;string, string&gt; tags = 6;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getTagsMap();
    /**
     * <pre>
     * map 类型
     * </pre>
     *
     * <code>map&lt;string, string&gt; tags = 6;</code>
     */

    /* nullable */
java.lang.String getTagsOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue);
    /**
     * <pre>
     * map 类型
     * </pre>
     *
     * <code>map&lt;string, string&gt; tags = 6;</code>
     */

    java.lang.String getTagsOrThrow(
        java.lang.String key);
  }
  /**
   * <pre>
   * 定义一个 message
   * </pre>
   *
   * Protobuf type {@code User}
   */
  public static final class User extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:User)
      UserOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private User() {
      name_ = "";
      email_ = "";
      gender_ = 0;
      phone_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new User();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private User(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              email_ = s;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              gender_ = rawValue;
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                phone_ = new java.util.ArrayList<io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber>();
                mutable_bitField0_ |= 0x00000001;
              }
              phone_.add(
                  input.readMessage(io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber.parser(), extensionRegistry));
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                tags_ = com.google.protobuf.MapField.newMapField(
                    TagsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000002;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              tags__ = input.readMessage(
                  TagsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              tags_.getMutableMap().put(
                  tags__.getKey(), tags__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          phone_ = java.util.Collections.unmodifiableList(phone_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.dunwu.javacore.serialize.stream.DemoProtos.internal_static_User_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetTags();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.dunwu.javacore.serialize.stream.DemoProtos.internal_static_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.dunwu.javacore.serialize.stream.DemoProtos.User.class, io.github.dunwu.javacore.serialize.stream.DemoProtos.User.Builder.class);
    }

    /**
     * <pre>
     * 定义一个枚举类型
     * </pre>
     *
     * Protobuf enum {@code User.Gender}
     */
    public enum Gender
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>DEFAULT = 0;</code>
       */
      DEFAULT(0),
      /**
       * <code>MALE = 1;</code>
       */
      MALE(1),
      /**
       * <pre>
       * 枚举值通常大写
       * </pre>
       *
       * <code>FEMALE = 2;</code>
       */
      FEMALE(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>DEFAULT = 0;</code>
       */
      public static final int DEFAULT_VALUE = 0;
      /**
       * <code>MALE = 1;</code>
       */
      public static final int MALE_VALUE = 1;
      /**
       * <pre>
       * 枚举值通常大写
       * </pre>
       *
       * <code>FEMALE = 2;</code>
       */
      public static final int FEMALE_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Gender valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Gender forNumber(int value) {
        switch (value) {
          case 0: return DEFAULT;
          case 1: return MALE;
          case 2: return FEMALE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Gender>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Gender> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Gender>() {
              public Gender findValueByNumber(int number) {
                return Gender.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return io.github.dunwu.javacore.serialize.stream.DemoProtos.User.getDescriptor().getEnumTypes().get(0);
      }

      private static final Gender[] VALUES = values();

      public static Gender valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Gender(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:User.Gender)
    }

    public interface PhoneNumberOrBuilder extends
        // @@protoc_insertion_point(interface_extends:User.PhoneNumber)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string number = 1;</code>
       * @return The number.
       */
      java.lang.String getNumber();
      /**
       * <code>string number = 1;</code>
       * @return The bytes for number.
       */
      com.google.protobuf.ByteString
          getNumberBytes();

      /**
       * <code>.User.PhoneNumber.PhoneType type = 2;</code>
       * @return The enum numeric value on the wire for type.
       */
      int getTypeValue();
      /**
       * <code>.User.PhoneNumber.PhoneType type = 2;</code>
       * @return The type.
       */
      io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber.PhoneType getType();
    }
    /**
     * <pre>
     * 定义一个 message 用于电话号码
     * </pre>
     *
     * Protobuf type {@code User.PhoneNumber}
     */
    public static final class PhoneNumber extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:User.PhoneNumber)
        PhoneNumberOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use PhoneNumber.newBuilder() to construct.
      private PhoneNumber(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private PhoneNumber() {
        number_ = "";
        type_ = 0;
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new PhoneNumber();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private PhoneNumber(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                number_ = s;
                break;
              }
              case 16: {
                int rawValue = input.readEnum();

                type_ = rawValue;
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.github.dunwu.javacore.serialize.stream.DemoProtos.internal_static_User_PhoneNumber_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.github.dunwu.javacore.serialize.stream.DemoProtos.internal_static_User_PhoneNumber_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber.class, io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber.Builder.class);
      }

      /**
       * Protobuf enum {@code User.PhoneNumber.PhoneType}
       */
      public enum PhoneType
          implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>MOBILE = 0;</code>
         */
        MOBILE(0),
        /**
         * <code>HOME = 1;</code>
         */
        HOME(1),
        /**
         * <code>WORK = 2;</code>
         */
        WORK(2),
        UNRECOGNIZED(-1),
        ;

        /**
         * <code>MOBILE = 0;</code>
         */
        public static final int MOBILE_VALUE = 0;
        /**
         * <code>HOME = 1;</code>
         */
        public static final int HOME_VALUE = 1;
        /**
         * <code>WORK = 2;</code>
         */
        public static final int WORK_VALUE = 2;


        public final int getNumber() {
          if (this == UNRECOGNIZED) {
            throw new java.lang.IllegalArgumentException(
                "Can't get the number of an unknown enum value.");
          }
          return value;
        }

        /**
         * @param value The numeric wire value of the corresponding enum entry.
         * @return The enum associated with the given numeric wire value.
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @java.lang.Deprecated
        public static PhoneType valueOf(int value) {
          return forNumber(value);
        }

        /**
         * @param value The numeric wire value of the corresponding enum entry.
         * @return The enum associated with the given numeric wire value.
         */
        public static PhoneType forNumber(int value) {
          switch (value) {
            case 0: return MOBILE;
            case 1: return HOME;
            case 2: return WORK;
            default: return null;
          }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<PhoneType>
            internalGetValueMap() {
          return internalValueMap;
        }
        private static final com.google.protobuf.Internal.EnumLiteMap<
            PhoneType> internalValueMap =
              new com.google.protobuf.Internal.EnumLiteMap<PhoneType>() {
                public PhoneType findValueByNumber(int number) {
                  return PhoneType.forNumber(number);
                }
              };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
          if (this == UNRECOGNIZED) {
            throw new java.lang.IllegalStateException(
                "Can't get the descriptor of an unrecognized enum value.");
          }
          return getDescriptor().getValues().get(ordinal());
        }
        public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
          return io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber.getDescriptor().getEnumTypes().get(0);
        }

        private static final PhoneType[] VALUES = values();

        public static PhoneType valueOf(
            com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
          if (desc.getType() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "EnumValueDescriptor is not for this type.");
          }
          if (desc.getIndex() == -1) {
            return UNRECOGNIZED;
          }
          return VALUES[desc.getIndex()];
        }

        private final int value;

        private PhoneType(int value) {
          this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:User.PhoneNumber.PhoneType)
      }

      public static final int NUMBER_FIELD_NUMBER = 1;
      private volatile java.lang.Object number_;
      /**
       * <code>string number = 1;</code>
       * @return The number.
       */
      @java.lang.Override
      public java.lang.String getNumber() {
        java.lang.Object ref = number_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          number_ = s;
          return s;
        }
      }
      /**
       * <code>string number = 1;</code>
       * @return The bytes for number.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getNumberBytes() {
        java.lang.Object ref = number_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          number_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int TYPE_FIELD_NUMBER = 2;
      private int type_;
      /**
       * <code>.User.PhoneNumber.PhoneType type = 2;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.User.PhoneNumber.PhoneType type = 2;</code>
       * @return The type.
       */
      @java.lang.Override public io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber.PhoneType getType() {
        @SuppressWarnings("deprecation")
        io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber.PhoneType result = io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber.PhoneType.valueOf(type_);
        return result == null ? io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber.PhoneType.UNRECOGNIZED : result;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(number_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, number_);
        }
        if (type_ != io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber.PhoneType.MOBILE.getNumber()) {
          output.writeEnum(2, type_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(number_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, number_);
        }
        if (type_ != io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber.PhoneType.MOBILE.getNumber()) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(2, type_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber)) {
          return super.equals(obj);
        }
        io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber other = (io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber) obj;

        if (!getNumber()
            .equals(other.getNumber())) return false;
        if (type_ != other.type_) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + NUMBER_FIELD_NUMBER;
        hash = (53 * hash) + getNumber().hashCode();
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * <pre>
       * 定义一个 message 用于电话号码
       * </pre>
       *
       * Protobuf type {@code User.PhoneNumber}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:User.PhoneNumber)
          io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumberOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return io.github.dunwu.javacore.serialize.stream.DemoProtos.internal_static_User_PhoneNumber_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return io.github.dunwu.javacore.serialize.stream.DemoProtos.internal_static_User_PhoneNumber_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber.class, io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber.Builder.class);
        }

        // Construct using io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          number_ = "";

          type_ = 0;

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return io.github.dunwu.javacore.serialize.stream.DemoProtos.internal_static_User_PhoneNumber_descriptor;
        }

        @java.lang.Override
        public io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber getDefaultInstanceForType() {
          return io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber.getDefaultInstance();
        }

        @java.lang.Override
        public io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber build() {
          io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber buildPartial() {
          io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber result = new io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber(this);
          result.number_ = number_;
          result.type_ = type_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber) {
            return mergeFrom((io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber other) {
          if (other == io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber.getDefaultInstance()) return this;
          if (!other.getNumber().isEmpty()) {
            number_ = other.number_;
            onChanged();
          }
          if (other.type_ != 0) {
            setTypeValue(other.getTypeValue());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object number_ = "";
        /**
         * <code>string number = 1;</code>
         * @return The number.
         */
        public java.lang.String getNumber() {
          java.lang.Object ref = number_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            number_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string number = 1;</code>
         * @return The bytes for number.
         */
        public com.google.protobuf.ByteString
            getNumberBytes() {
          java.lang.Object ref = number_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            number_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string number = 1;</code>
         * @param value The number to set.
         * @return This builder for chaining.
         */
        public Builder setNumber(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          number_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string number = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearNumber() {
          
          number_ = getDefaultInstance().getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>string number = 1;</code>
         * @param value The bytes for number to set.
         * @return This builder for chaining.
         */
        public Builder setNumberBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          number_ = value;
          onChanged();
          return this;
        }

        private int type_ = 0;
        /**
         * <code>.User.PhoneNumber.PhoneType type = 2;</code>
         * @return The enum numeric value on the wire for type.
         */
        @java.lang.Override public int getTypeValue() {
          return type_;
        }
        /**
         * <code>.User.PhoneNumber.PhoneType type = 2;</code>
         * @param value The enum numeric value on the wire for type to set.
         * @return This builder for chaining.
         */
        public Builder setTypeValue(int value) {
          
          type_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>.User.PhoneNumber.PhoneType type = 2;</code>
         * @return The type.
         */
        @java.lang.Override
        public io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber.PhoneType getType() {
          @SuppressWarnings("deprecation")
          io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber.PhoneType result = io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber.PhoneType.valueOf(type_);
          return result == null ? io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber.PhoneType.UNRECOGNIZED : result;
        }
        /**
         * <code>.User.PhoneNumber.PhoneType type = 2;</code>
         * @param value The type to set.
         * @return This builder for chaining.
         */
        public Builder setType(io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber.PhoneType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          
          type_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>.User.PhoneNumber.PhoneType type = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearType() {
          
          type_ = 0;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:User.PhoneNumber)
      }

      // @@protoc_insertion_point(class_scope:User.PhoneNumber)
      private static final io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber();
      }

      public static io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<PhoneNumber>
          PARSER = new com.google.protobuf.AbstractParser<PhoneNumber>() {
        @java.lang.Override
        public PhoneNumber parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new PhoneNumber(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<PhoneNumber> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<PhoneNumber> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <pre>
     * int 类型
     * </pre>
     *
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <pre>
     * string 类型
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * string 类型
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 3;
    private volatile java.lang.Object email_;
    /**
     * <code>string email = 3;</code>
     * @return The email.
     */
    @java.lang.Override
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>string email = 3;</code>
     * @return The bytes for email.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GENDER_FIELD_NUMBER = 4;
    private int gender_;
    /**
     * <pre>
     * 引用下面定义的 Gender 枚举类型
     * </pre>
     *
     * <code>.User.Gender gender = 4;</code>
     * @return The enum numeric value on the wire for gender.
     */
    @java.lang.Override public int getGenderValue() {
      return gender_;
    }
    /**
     * <pre>
     * 引用下面定义的 Gender 枚举类型
     * </pre>
     *
     * <code>.User.Gender gender = 4;</code>
     * @return The gender.
     */
    @java.lang.Override public io.github.dunwu.javacore.serialize.stream.DemoProtos.User.Gender getGender() {
      @SuppressWarnings("deprecation")
      io.github.dunwu.javacore.serialize.stream.DemoProtos.User.Gender result = io.github.dunwu.javacore.serialize.stream.DemoProtos.User.Gender.valueOf(gender_);
      return result == null ? io.github.dunwu.javacore.serialize.stream.DemoProtos.User.Gender.UNRECOGNIZED : result;
    }

    public static final int PHONE_FIELD_NUMBER = 5;
    private java.util.List<io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber> phone_;
    /**
     * <pre>
     * 引用下面定义的 PhoneNumber 类型的 message
     * </pre>
     *
     * <code>repeated .User.PhoneNumber phone = 5;</code>
     */
    @java.lang.Override
    public java.util.List<io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber> getPhoneList() {
      return phone_;
    }
    /**
     * <pre>
     * 引用下面定义的 PhoneNumber 类型的 message
     * </pre>
     *
     * <code>repeated .User.PhoneNumber phone = 5;</code>
     */
    @java.lang.Override
    public java.util.List<? extends io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumberOrBuilder> 
        getPhoneOrBuilderList() {
      return phone_;
    }
    /**
     * <pre>
     * 引用下面定义的 PhoneNumber 类型的 message
     * </pre>
     *
     * <code>repeated .User.PhoneNumber phone = 5;</code>
     */
    @java.lang.Override
    public int getPhoneCount() {
      return phone_.size();
    }
    /**
     * <pre>
     * 引用下面定义的 PhoneNumber 类型的 message
     * </pre>
     *
     * <code>repeated .User.PhoneNumber phone = 5;</code>
     */
    @java.lang.Override
    public io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber getPhone(int index) {
      return phone_.get(index);
    }
    /**
     * <pre>
     * 引用下面定义的 PhoneNumber 类型的 message
     * </pre>
     *
     * <code>repeated .User.PhoneNumber phone = 5;</code>
     */
    @java.lang.Override
    public io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumberOrBuilder getPhoneOrBuilder(
        int index) {
      return phone_.get(index);
    }

    public static final int TAGS_FIELD_NUMBER = 6;
    private static final class TagsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  io.github.dunwu.javacore.serialize.stream.DemoProtos.internal_static_User_TagsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> tags_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetTags() {
      if (tags_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            TagsDefaultEntryHolder.defaultEntry);
      }
      return tags_;
    }

    public int getTagsCount() {
      return internalGetTags().getMap().size();
    }
    /**
     * <pre>
     * map 类型
     * </pre>
     *
     * <code>map&lt;string, string&gt; tags = 6;</code>
     */

    @java.lang.Override
    public boolean containsTags(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetTags().getMap().containsKey(key);
    }
    /**
     * Use {@link #getTagsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getTags() {
      return getTagsMap();
    }
    /**
     * <pre>
     * map 类型
     * </pre>
     *
     * <code>map&lt;string, string&gt; tags = 6;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getTagsMap() {
      return internalGetTags().getMap();
    }
    /**
     * <pre>
     * map 类型
     * </pre>
     *
     * <code>map&lt;string, string&gt; tags = 6;</code>
     */
    @java.lang.Override

    public java.lang.String getTagsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetTags().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * map 类型
     * </pre>
     *
     * <code>map&lt;string, string&gt; tags = 6;</code>
     */
    @java.lang.Override

    public java.lang.String getTagsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetTags().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, email_);
      }
      if (gender_ != io.github.dunwu.javacore.serialize.stream.DemoProtos.User.Gender.DEFAULT.getNumber()) {
        output.writeEnum(4, gender_);
      }
      for (int i = 0; i < phone_.size(); i++) {
        output.writeMessage(5, phone_.get(i));
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetTags(),
          TagsDefaultEntryHolder.defaultEntry,
          6);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, email_);
      }
      if (gender_ != io.github.dunwu.javacore.serialize.stream.DemoProtos.User.Gender.DEFAULT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, gender_);
      }
      for (int i = 0; i < phone_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, phone_.get(i));
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetTags().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        tags__ = TagsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(6, tags__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.github.dunwu.javacore.serialize.stream.DemoProtos.User)) {
        return super.equals(obj);
      }
      io.github.dunwu.javacore.serialize.stream.DemoProtos.User other = (io.github.dunwu.javacore.serialize.stream.DemoProtos.User) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getEmail()
          .equals(other.getEmail())) return false;
      if (gender_ != other.gender_) return false;
      if (!getPhoneList()
          .equals(other.getPhoneList())) return false;
      if (!internalGetTags().equals(
          other.internalGetTags())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      hash = (37 * hash) + GENDER_FIELD_NUMBER;
      hash = (53 * hash) + gender_;
      if (getPhoneCount() > 0) {
        hash = (37 * hash) + PHONE_FIELD_NUMBER;
        hash = (53 * hash) + getPhoneList().hashCode();
      }
      if (!internalGetTags().getMap().isEmpty()) {
        hash = (37 * hash) + TAGS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetTags().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.github.dunwu.javacore.serialize.stream.DemoProtos.User parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.dunwu.javacore.serialize.stream.DemoProtos.User parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.dunwu.javacore.serialize.stream.DemoProtos.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.dunwu.javacore.serialize.stream.DemoProtos.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.dunwu.javacore.serialize.stream.DemoProtos.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.dunwu.javacore.serialize.stream.DemoProtos.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.dunwu.javacore.serialize.stream.DemoProtos.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.dunwu.javacore.serialize.stream.DemoProtos.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.dunwu.javacore.serialize.stream.DemoProtos.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.github.dunwu.javacore.serialize.stream.DemoProtos.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.dunwu.javacore.serialize.stream.DemoProtos.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.dunwu.javacore.serialize.stream.DemoProtos.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.github.dunwu.javacore.serialize.stream.DemoProtos.User prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 定义一个 message
     * </pre>
     *
     * Protobuf type {@code User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:User)
        io.github.dunwu.javacore.serialize.stream.DemoProtos.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.github.dunwu.javacore.serialize.stream.DemoProtos.internal_static_User_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 6:
            return internalGetTags();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 6:
            return internalGetMutableTags();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.github.dunwu.javacore.serialize.stream.DemoProtos.internal_static_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.github.dunwu.javacore.serialize.stream.DemoProtos.User.class, io.github.dunwu.javacore.serialize.stream.DemoProtos.User.Builder.class);
      }

      // Construct using io.github.dunwu.javacore.serialize.stream.DemoProtos.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPhoneFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        email_ = "";

        gender_ = 0;

        if (phoneBuilder_ == null) {
          phone_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          phoneBuilder_.clear();
        }
        internalGetMutableTags().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.github.dunwu.javacore.serialize.stream.DemoProtos.internal_static_User_descriptor;
      }

      @java.lang.Override
      public io.github.dunwu.javacore.serialize.stream.DemoProtos.User getDefaultInstanceForType() {
        return io.github.dunwu.javacore.serialize.stream.DemoProtos.User.getDefaultInstance();
      }

      @java.lang.Override
      public io.github.dunwu.javacore.serialize.stream.DemoProtos.User build() {
        io.github.dunwu.javacore.serialize.stream.DemoProtos.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.github.dunwu.javacore.serialize.stream.DemoProtos.User buildPartial() {
        io.github.dunwu.javacore.serialize.stream.DemoProtos.User result = new io.github.dunwu.javacore.serialize.stream.DemoProtos.User(this);
        int from_bitField0_ = bitField0_;
        result.id_ = id_;
        result.name_ = name_;
        result.email_ = email_;
        result.gender_ = gender_;
        if (phoneBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            phone_ = java.util.Collections.unmodifiableList(phone_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.phone_ = phone_;
        } else {
          result.phone_ = phoneBuilder_.build();
        }
        result.tags_ = internalGetTags();
        result.tags_.makeImmutable();
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.github.dunwu.javacore.serialize.stream.DemoProtos.User) {
          return mergeFrom((io.github.dunwu.javacore.serialize.stream.DemoProtos.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.github.dunwu.javacore.serialize.stream.DemoProtos.User other) {
        if (other == io.github.dunwu.javacore.serialize.stream.DemoProtos.User.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          onChanged();
        }
        if (other.gender_ != 0) {
          setGenderValue(other.getGenderValue());
        }
        if (phoneBuilder_ == null) {
          if (!other.phone_.isEmpty()) {
            if (phone_.isEmpty()) {
              phone_ = other.phone_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePhoneIsMutable();
              phone_.addAll(other.phone_);
            }
            onChanged();
          }
        } else {
          if (!other.phone_.isEmpty()) {
            if (phoneBuilder_.isEmpty()) {
              phoneBuilder_.dispose();
              phoneBuilder_ = null;
              phone_ = other.phone_;
              bitField0_ = (bitField0_ & ~0x00000001);
              phoneBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPhoneFieldBuilder() : null;
            } else {
              phoneBuilder_.addAllMessages(other.phone_);
            }
          }
        }
        internalGetMutableTags().mergeFrom(
            other.internalGetTags());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.github.dunwu.javacore.serialize.stream.DemoProtos.User parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.github.dunwu.javacore.serialize.stream.DemoProtos.User) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <pre>
       * int 类型
       * </pre>
       *
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <pre>
       * int 类型
       * </pre>
       *
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * int 类型
       * </pre>
       *
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <pre>
       * string 类型
       * </pre>
       *
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * string 类型
       * </pre>
       *
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * string 类型
       * </pre>
       *
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * string 类型
       * </pre>
       *
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * string 类型
       * </pre>
       *
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>string email = 3;</code>
       * @return The email.
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string email = 3;</code>
       * @return The bytes for email.
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string email = 3;</code>
       * @param value The email to set.
       * @return This builder for chaining.
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string email = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmail() {
        
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>string email = 3;</code>
       * @param value The bytes for email to set.
       * @return This builder for chaining.
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        email_ = value;
        onChanged();
        return this;
      }

      private int gender_ = 0;
      /**
       * <pre>
       * 引用下面定义的 Gender 枚举类型
       * </pre>
       *
       * <code>.User.Gender gender = 4;</code>
       * @return The enum numeric value on the wire for gender.
       */
      @java.lang.Override public int getGenderValue() {
        return gender_;
      }
      /**
       * <pre>
       * 引用下面定义的 Gender 枚举类型
       * </pre>
       *
       * <code>.User.Gender gender = 4;</code>
       * @param value The enum numeric value on the wire for gender to set.
       * @return This builder for chaining.
       */
      public Builder setGenderValue(int value) {
        
        gender_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 引用下面定义的 Gender 枚举类型
       * </pre>
       *
       * <code>.User.Gender gender = 4;</code>
       * @return The gender.
       */
      @java.lang.Override
      public io.github.dunwu.javacore.serialize.stream.DemoProtos.User.Gender getGender() {
        @SuppressWarnings("deprecation")
        io.github.dunwu.javacore.serialize.stream.DemoProtos.User.Gender result = io.github.dunwu.javacore.serialize.stream.DemoProtos.User.Gender.valueOf(gender_);
        return result == null ? io.github.dunwu.javacore.serialize.stream.DemoProtos.User.Gender.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 引用下面定义的 Gender 枚举类型
       * </pre>
       *
       * <code>.User.Gender gender = 4;</code>
       * @param value The gender to set.
       * @return This builder for chaining.
       */
      public Builder setGender(io.github.dunwu.javacore.serialize.stream.DemoProtos.User.Gender value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        gender_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 引用下面定义的 Gender 枚举类型
       * </pre>
       *
       * <code>.User.Gender gender = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearGender() {
        
        gender_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber> phone_ =
        java.util.Collections.emptyList();
      private void ensurePhoneIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          phone_ = new java.util.ArrayList<io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber>(phone_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber, io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber.Builder, io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumberOrBuilder> phoneBuilder_;

      /**
       * <pre>
       * 引用下面定义的 PhoneNumber 类型的 message
       * </pre>
       *
       * <code>repeated .User.PhoneNumber phone = 5;</code>
       */
      public java.util.List<io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber> getPhoneList() {
        if (phoneBuilder_ == null) {
          return java.util.Collections.unmodifiableList(phone_);
        } else {
          return phoneBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * 引用下面定义的 PhoneNumber 类型的 message
       * </pre>
       *
       * <code>repeated .User.PhoneNumber phone = 5;</code>
       */
      public int getPhoneCount() {
        if (phoneBuilder_ == null) {
          return phone_.size();
        } else {
          return phoneBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * 引用下面定义的 PhoneNumber 类型的 message
       * </pre>
       *
       * <code>repeated .User.PhoneNumber phone = 5;</code>
       */
      public io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber getPhone(int index) {
        if (phoneBuilder_ == null) {
          return phone_.get(index);
        } else {
          return phoneBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * 引用下面定义的 PhoneNumber 类型的 message
       * </pre>
       *
       * <code>repeated .User.PhoneNumber phone = 5;</code>
       */
      public Builder setPhone(
          int index, io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber value) {
        if (phoneBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhoneIsMutable();
          phone_.set(index, value);
          onChanged();
        } else {
          phoneBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 引用下面定义的 PhoneNumber 类型的 message
       * </pre>
       *
       * <code>repeated .User.PhoneNumber phone = 5;</code>
       */
      public Builder setPhone(
          int index, io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber.Builder builderForValue) {
        if (phoneBuilder_ == null) {
          ensurePhoneIsMutable();
          phone_.set(index, builderForValue.build());
          onChanged();
        } else {
          phoneBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 引用下面定义的 PhoneNumber 类型的 message
       * </pre>
       *
       * <code>repeated .User.PhoneNumber phone = 5;</code>
       */
      public Builder addPhone(io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber value) {
        if (phoneBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhoneIsMutable();
          phone_.add(value);
          onChanged();
        } else {
          phoneBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * 引用下面定义的 PhoneNumber 类型的 message
       * </pre>
       *
       * <code>repeated .User.PhoneNumber phone = 5;</code>
       */
      public Builder addPhone(
          int index, io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber value) {
        if (phoneBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhoneIsMutable();
          phone_.add(index, value);
          onChanged();
        } else {
          phoneBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 引用下面定义的 PhoneNumber 类型的 message
       * </pre>
       *
       * <code>repeated .User.PhoneNumber phone = 5;</code>
       */
      public Builder addPhone(
          io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber.Builder builderForValue) {
        if (phoneBuilder_ == null) {
          ensurePhoneIsMutable();
          phone_.add(builderForValue.build());
          onChanged();
        } else {
          phoneBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 引用下面定义的 PhoneNumber 类型的 message
       * </pre>
       *
       * <code>repeated .User.PhoneNumber phone = 5;</code>
       */
      public Builder addPhone(
          int index, io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber.Builder builderForValue) {
        if (phoneBuilder_ == null) {
          ensurePhoneIsMutable();
          phone_.add(index, builderForValue.build());
          onChanged();
        } else {
          phoneBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 引用下面定义的 PhoneNumber 类型的 message
       * </pre>
       *
       * <code>repeated .User.PhoneNumber phone = 5;</code>
       */
      public Builder addAllPhone(
          java.lang.Iterable<? extends io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber> values) {
        if (phoneBuilder_ == null) {
          ensurePhoneIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, phone_);
          onChanged();
        } else {
          phoneBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * 引用下面定义的 PhoneNumber 类型的 message
       * </pre>
       *
       * <code>repeated .User.PhoneNumber phone = 5;</code>
       */
      public Builder clearPhone() {
        if (phoneBuilder_ == null) {
          phone_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          phoneBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 引用下面定义的 PhoneNumber 类型的 message
       * </pre>
       *
       * <code>repeated .User.PhoneNumber phone = 5;</code>
       */
      public Builder removePhone(int index) {
        if (phoneBuilder_ == null) {
          ensurePhoneIsMutable();
          phone_.remove(index);
          onChanged();
        } else {
          phoneBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * 引用下面定义的 PhoneNumber 类型的 message
       * </pre>
       *
       * <code>repeated .User.PhoneNumber phone = 5;</code>
       */
      public io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber.Builder getPhoneBuilder(
          int index) {
        return getPhoneFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * 引用下面定义的 PhoneNumber 类型的 message
       * </pre>
       *
       * <code>repeated .User.PhoneNumber phone = 5;</code>
       */
      public io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumberOrBuilder getPhoneOrBuilder(
          int index) {
        if (phoneBuilder_ == null) {
          return phone_.get(index);  } else {
          return phoneBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * 引用下面定义的 PhoneNumber 类型的 message
       * </pre>
       *
       * <code>repeated .User.PhoneNumber phone = 5;</code>
       */
      public java.util.List<? extends io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumberOrBuilder> 
           getPhoneOrBuilderList() {
        if (phoneBuilder_ != null) {
          return phoneBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(phone_);
        }
      }
      /**
       * <pre>
       * 引用下面定义的 PhoneNumber 类型的 message
       * </pre>
       *
       * <code>repeated .User.PhoneNumber phone = 5;</code>
       */
      public io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber.Builder addPhoneBuilder() {
        return getPhoneFieldBuilder().addBuilder(
            io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber.getDefaultInstance());
      }
      /**
       * <pre>
       * 引用下面定义的 PhoneNumber 类型的 message
       * </pre>
       *
       * <code>repeated .User.PhoneNumber phone = 5;</code>
       */
      public io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber.Builder addPhoneBuilder(
          int index) {
        return getPhoneFieldBuilder().addBuilder(
            index, io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber.getDefaultInstance());
      }
      /**
       * <pre>
       * 引用下面定义的 PhoneNumber 类型的 message
       * </pre>
       *
       * <code>repeated .User.PhoneNumber phone = 5;</code>
       */
      public java.util.List<io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber.Builder> 
           getPhoneBuilderList() {
        return getPhoneFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber, io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber.Builder, io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumberOrBuilder> 
          getPhoneFieldBuilder() {
        if (phoneBuilder_ == null) {
          phoneBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber, io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumber.Builder, io.github.dunwu.javacore.serialize.stream.DemoProtos.User.PhoneNumberOrBuilder>(
                  phone_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          phone_ = null;
        }
        return phoneBuilder_;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> tags_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetTags() {
        if (tags_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              TagsDefaultEntryHolder.defaultEntry);
        }
        return tags_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableTags() {
        onChanged();;
        if (tags_ == null) {
          tags_ = com.google.protobuf.MapField.newMapField(
              TagsDefaultEntryHolder.defaultEntry);
        }
        if (!tags_.isMutable()) {
          tags_ = tags_.copy();
        }
        return tags_;
      }

      public int getTagsCount() {
        return internalGetTags().getMap().size();
      }
      /**
       * <pre>
       * map 类型
       * </pre>
       *
       * <code>map&lt;string, string&gt; tags = 6;</code>
       */

      @java.lang.Override
      public boolean containsTags(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        return internalGetTags().getMap().containsKey(key);
      }
      /**
       * Use {@link #getTagsMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getTags() {
        return getTagsMap();
      }
      /**
       * <pre>
       * map 类型
       * </pre>
       *
       * <code>map&lt;string, string&gt; tags = 6;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.String, java.lang.String> getTagsMap() {
        return internalGetTags().getMap();
      }
      /**
       * <pre>
       * map 类型
       * </pre>
       *
       * <code>map&lt;string, string&gt; tags = 6;</code>
       */
      @java.lang.Override

      public java.lang.String getTagsOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetTags().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       * map 类型
       * </pre>
       *
       * <code>map&lt;string, string&gt; tags = 6;</code>
       */
      @java.lang.Override

      public java.lang.String getTagsOrThrow(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetTags().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearTags() {
        internalGetMutableTags().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       * map 类型
       * </pre>
       *
       * <code>map&lt;string, string&gt; tags = 6;</code>
       */

      public Builder removeTags(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        internalGetMutableTags().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableTags() {
        return internalGetMutableTags().getMutableMap();
      }
      /**
       * <pre>
       * map 类型
       * </pre>
       *
       * <code>map&lt;string, string&gt; tags = 6;</code>
       */
      public Builder putTags(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new NullPointerException("map key"); }
        if (value == null) {
  throw new NullPointerException("map value");
}

        internalGetMutableTags().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <pre>
       * map 类型
       * </pre>
       *
       * <code>map&lt;string, string&gt; tags = 6;</code>
       */

      public Builder putAllTags(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableTags().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:User)
    }

    // @@protoc_insertion_point(class_scope:User)
    private static final io.github.dunwu.javacore.serialize.stream.DemoProtos.User DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.github.dunwu.javacore.serialize.stream.DemoProtos.User();
    }

    public static io.github.dunwu.javacore.serialize.stream.DemoProtos.User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<User>
        PARSER = new com.google.protobuf.AbstractParser<User>() {
      @java.lang.Override
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new User(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<User> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.github.dunwu.javacore.serialize.stream.DemoProtos.User getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_User_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_User_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_User_TagsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_User_TagsEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_User_PhoneNumber_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_User_PhoneNumber_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ndemo.proto\"\337\002\n\004User\022\n\n\002id\030\001 \001(\005\022\014\n\004nam" +
      "e\030\002 \001(\t\022\r\n\005email\030\003 \001(\t\022\034\n\006gender\030\004 \001(\0162\014" +
      ".User.Gender\022 \n\005phone\030\005 \003(\0132\021.User.Phone" +
      "Number\022\035\n\004tags\030\006 \003(\0132\017.User.TagsEntry\032+\n" +
      "\tTagsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\002" +
      "8\001\032u\n\013PhoneNumber\022\016\n\006number\030\001 \001(\t\022)\n\004typ" +
      "e\030\002 \001(\0162\033.User.PhoneNumber.PhoneType\"+\n\t" +
      "PhoneType\022\n\n\006MOBILE\020\000\022\010\n\004HOME\020\001\022\010\n\004WORK\020" +
      "\002\"+\n\006Gender\022\013\n\007DEFAULT\020\000\022\010\n\004MALE\020\001\022\n\n\006FE" +
      "MALE\020\002B7\n)io.github.dunwu.javacore.seria" +
      "lize.streamB\nDemoProtosb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_User_descriptor,
        new java.lang.String[] { "Id", "Name", "Email", "Gender", "Phone", "Tags", });
    internal_static_User_TagsEntry_descriptor =
      internal_static_User_descriptor.getNestedTypes().get(0);
    internal_static_User_TagsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_User_TagsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_User_PhoneNumber_descriptor =
      internal_static_User_descriptor.getNestedTypes().get(1);
    internal_static_User_PhoneNumber_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_User_PhoneNumber_descriptor,
        new java.lang.String[] { "Number", "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
